@host=https://localhost:32801

POST {{host}}/authentication/register
Content-Type: application/json

{
    "FirstName": "Luiz",
    "LastName": "Tessarolli",
    "email": "luiz@tt1.com.br",
    "password": "my@pw123"
}