@host=https://localhost:5001

POST {{host}}/authentication/register
Content-Type: application/json

{
    "FirstName": "a",
    "LastName": "a",
    "email": "luiz@tt1.com.br",
    "password": "my@pw123"
}