@host=https://localhost:5001

POST {{host}}/authentication/register
Content-Type: application/json

{
    "FirstName": "Admin",
    "LastName": "Admin",
    "email": "admin@documentally.com",
    "password": "admin"
}